### ISSUE TITLE
AUDIO INPUT NOT PAUSING ON PAUSECOMPLETE

### ISSUE THREAD

**Issue by MalikMahnoor** [ashishbajaj99/mic#16]
on pauseComplete signal,I dont see find speech block statement but afterwards when i play the audio it includes the voice input given when the mic was actually paused.What can be the reason behind this?

**Comment by ashishbajaj99** [comment]
Since the application works at a higher layer, sometimes it could be slowed down by available system resources and is not guaranteed to be running in a real time manner. This is more a limitation of the fact that the Mac/Linux/Raspbian/Windows are not real time systems. So in such cases there will be some residual data that gets buffered...

Other than that no other reason that I can think of.
