### ISSUE TITLE
After some time, "recording audioProcess has exited with code = 0"

### ISSUE THREAD

**Issue by chandwki** [ashishbajaj99/mic#22]
I am using this package to capture audio input for days on end. It seems after a few hours it quits.

With debug set to true I see this error in the log,

> recording audioProcess has exited with code = 0

Anyone else run in to this issue?

**Comment by chandwki** [comment]
This seems to happen consistently after around 111851xx milliseconds of capture. A little over three hours.

**Comment by cmvee** [comment]
I'm having this same issue. It exits, consistently, at 1 hr, 33 mins, and 12 seconds. That's also 5592 seconds, or of course 5,592,000 ms, which is basically half of your 111851xx ms number, which I find interesting. My recording options are 2 channels, 32-bit, 48000 Hz, signed integer, little endian.

Have you found a resolution to this issue? I am starting to think it is an issue with the arecord executable that this code is calling.

**Comment by chandwki** [comment]
@cmvee I've been meaning to look into this issue, thanks for reminding me.

Just curious what distro are you using and what version of arecord is installed on it? I'm having this issue on a Raspberry Pi running Raspbian 9.1 and arecord version 1.1.3

**Comment by cmvee** [comment]
@chandwki I am running latest Raspbian Stretch. `uname -a` gives `Linux 4.14.30-v7+ #1102 SMP Mon Mar 26 16:45:49 BST 2018 armv7l GNU/Linux`. I've tested in a Pi 3B and 3B+. Both have issues.

I edited the mic code and found that having it use sox instead of arecord resolves the issue, so this means it's a limitation of arecord, but I still haven't determined the root cause of why arecord exits.

**Comment by chandwki** [comment]
@cmvee well done!

@ashishbajaj99 I can confirm that PR #25 fixes this issue for me. Could you please merge it?

**Comment by ashishbajaj99** [comment]
Sure, thanks a lot guys!
________________________________
